// Whitelist sketchy sites since 1904
const domainWhitelist = [
	"discord.com",
	"www.discord.com",
	"discordapp.com",
	"www.discordapp.com",
	"media.discordapp.net",
	"tenor.com",
	"www.tenor.com",
	"twitch.tv",
	"www.twitch.tv",
	"youtu.be.com",
	"www.youtu.be.com",
	"youtube.com",
	"www.youtube.com",
	"medal.tv",
	"www.medal.tv",
	"streamable.com",
	"www.streamable.com",
	"instagram.com",
	"www.instagram.com",
	"tiktok.com",
	"www.tiktok.com",
	"vm.tiktok.com",
	"forms.gle",
	"www.forms.gle",
	"media.discordapp.net",
	"cdn.discordapp.net",
	"cdn.discordapp.com",
	"youtu.be",
	"we.tl",
	"tebex.io",
	"atlanticroleplay.tebex.io",
	"clips.twitch.tv",
	"docs.google.com",
	"govatlantic.at.ua",
];

exports.domainWhitelist = domainWhitelist;